### ISSUE TITLE
Solution for the Current Problem 

### ISSUE THREAD

**Issue by Abrahamkazerian** [altimetrik-onboarding-uy/akazerian#3]
The problem to solve is to mark a habit as complete without changing the status of it, since for them the only two things that matter are to whom is given the task to and the name of the task it self and at the same time track all the changes made to the habit.

The solution found to this problem is to create a custom field in a custom object, the field will be a check box letting the user mark as completed if not mark it will be assumed that it has not been completed successfully, this will let tell if the task is done or not solving one of the problems, this solution guide us to create a second custom object that will save the changes made to the "completion" or "In-completion" of the habit this will let us track it, the second custom object that we will call it for sake of clarity will be HabitTracker this must have a Master-Details relationship to our first object that it will be call Habitica

**Comment by rjulianialtimetrik** [comment]
You missed the part the new object must have a master-detail or lookup relationship to your main habit object.
